name: Build from Glyphs

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # A release, pre-release, or draft of a release was published
    types: [published]
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout ${{ github.head_ref || github.ref_name }}
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: .github/python-version.txt
        cache: pip
    - name: Build variable fonts
      run: make build
    - name: Build Android fonts
      run: make android
    - name: Generate artifact name
      id: zip-name
      uses: alpha-tango-kilo/gha-artifact-name@49459760611c4a5cedffa13dfb36ca29ab1fdcfc # v1.3.0
      with:
        repo-name: Google Sans Code
        overrides: |
          build-test: build
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ steps.zip-name.outputs.artifact-name }}
        path: |
          fonts/
    outputs:
      artifact-name: ${{ steps.zip-name.outputs.artifact-name }}
  tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs:
    - build
    steps:
    - name: Checkout ${{ github.head_ref || github.ref_name }}
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        persist-credentials: false
    - name: Download built fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ needs.build.outputs.artifact-name }}
        path: fonts
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: .github/python-version.txt
        cache: pip
    - name: OpenType Sanitizer checks
      uses: f-actions/opentype-sanitizer@d5603373a9adccd136dd48b037b9b5178b485bea # v4.0.0
      with:
        path: fonts/**/*.ttf
    - name: Shaperglot report
      run: |
        echo "::group::Set up venv"
        python -m venv shaperglot-venv
        shaperglot-venv/bin/pip install --upgrade shaperglot
        echo "::endgroup::"
        shaperglot-venv/bin/shaperglot report fonts/variable/GoogleSansCode[MONO,wght].ttf
    - name: Run Fontbakery
      id: fontbakery
      run: |
        mkdir -p venv
        touch venv/touchfile build.stamp
        make test
    - name: Upload Fontbakery report(s)
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      # Always upload reports (even during a pipeline fail), so long as Fontbakery completed
      if: ${{ !cancelled() && (steps.fontbakery.conclusion == 'success' || steps.fontbakery.conclusion == 'failure') }}
      with:
        name: Fontbakery reports
        path: out/fontbakery
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
    - build
    - tests
    # Only run on a GitHub release
    if: github.event_name == 'release'
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout ${{ github.head_ref || github.ref_name }}
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        persist-credentials: false
    - name: Download built fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ needs.build.outputs.artifact-name }}
    - name: Create release archives
      run: |
        cp "$GITHUB_WORKSPACE/OFL.txt" "$GITHUB_WORKSPACE/variable"
        cd "$GITHUB_WORKSPACE/variable" \
          && zip "../GoogleSansCode-${GITHUB_REF#refs/*/}.zip" OFL.txt *.ttf
        
        cp "$GITHUB_WORKSPACE/OFL.txt" "$GITHUB_WORKSPACE/android"
        cd "$GITHUB_WORKSPACE/android" \
          && zip "../GoogleSansCode-Android-${GITHUB_REF#refs/*/}.zip" OFL.txt *.ttf
        
        cd "$GITHUB_WORKSPACE"
        # Repo must be explicitly stated as we don't have the repo checked out
        gh release upload --repo "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" \
          GoogleSansCode*.zip
