name: Diffenate builds

on:
  workflow_dispatch:
    inputs:
      before:
        description: The 'before' git reference (tag, branch, or commit)
        required: true
      after:
        description: The 'after' git reference (tag, branch, or commit)
        required: true

permissions:
  contents: read

jobs:
  build-before:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout ${{ inputs.before }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.before }}
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: .github/python-version.txt
        cache: pip
    - name: Setup venv
      run: make setup
    - name: Build fonts
      run: source .venv/bin/activate && make build
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Before VFs (${{ inputs.before }})
        path: fonts/variable
  build-after:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Checkout ${{ inputs.after }}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ inputs.after }}
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: .github/python-version.txt
        cache: pip
    - name: Setup venv
      run: make setup
    - name: Build fonts
      run: source .venv/bin/activate && make build
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: After VFs (${{ inputs.after }})
        path: fonts/variable
  diffenate:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    needs:
    - build-before
    - build-after
    steps:
    - name: Checkout python-version.txt from main
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: .github/python-version.txt
        persist-credentials: false
    - name: Download before fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Before VFs (${{ inputs.before }})
        path: before
    - name: Download after fonts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: After VFs (${{ inputs.after }})
        path: after
    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version-file: .github/python-version.txt
        cache: pip
    - name: Install diffenator2
      run: pip install --upgrade diffenator2
    - name: Run diffenator2
      run: |
        mkdir -p diffenator_report
        diffenator2 diff --fonts-before before/*.ttf --fonts-after after/*.ttf \
          --out diffenator_report
    - name: Upload diffenator report
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Diffenator2 report (${{ inputs.before }} vs ${{ inputs.after }})
        path: diffenator_report
